### ISSUE TITLE
关于Russia与Russian

### ISSUE THREAD

**Issue by Fibird** [OOP-PRACTICE/Tetris-game#14]
这是这两个单词对应的发音，点击相应单词即可查看读音。
- [Russia](http://fanyi.baidu.com/?aldtype=85&#en/zh/Russia)
- [Russian](http://fanyi.baidu.com/?aldtype=85&#en/zh/Russian)

我今天将[Russia](http://fanyi.baidu.com/?aldtype=85&#en/zh/Russia)读成了[Russian](http://fanyi.baidu.com/?aldtype=85&#en/zh/Russian)，在这里纠正一下。 @YuqiangChi @JiangLuan

**Comment by YuqiangChi** [comment]
Good !
